mkdir build
cd build

REM Configure step
set CMAKE_CUSTOM=
cmake^
 -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX%^
 -DCMAKE_INSTALL_PREFIX:PATH=%LIBRARY_PREFIX%^
 -DSimpleITK_BUILD_DISTRIBUTE:BOOL=ON^
 -DSimpleITK_BUILD_STRIP:BOOL=ON^
 -DBUILD_SHARED_LIBS:BOOL=OFF^
 -DWRAP_CSHARP:BOOL=OFF^
 -DWRAP_LUA:BOOL=OFF^
 -DWRAP_PYTHON:BOOL=ON^
 -DWRAP_JAVA:BOOL=OFF^
 -DWRAP_CSHARP:BOOL=OFF^
 -DWRAP_TCL:BOOL=OFF^
 -DWRAP_R:BOOL=OFF^
 -DWRAP_RUBY:BOOL=OFF^
 -DITK_USE_SYSTEM_JPEG:BOOL=ON^
 -DITK_USE_SYSTEM_PNG:BOOL=ON^
 -DITK_USE_SYSTEM_TIFF:BOOL=ON^
 -DITK_USE_SYSTEM_ZLIB:BOOL=ON^
 -D"PYTHON_EXECUTABLE:FILEPATH=%PYTHON%"^
 -D"PYTHON_INCLUDE_PATH:PATH=%LIBRARY_INC%"^
 -D"PYTHON_LIBRARY:FILEPATH=%LIBRARY_LIB%/python${PY_VER}.lib^
 "${SRC_DIR}/SuperBuild"
if errorlevel 1 exit 1

REM Build step
cmake --build . --config Release
if errorlevel 1 exit 1

REM Install step
cmake --build . --config Release --target INSTALL
if errorlevel 1 exit 1
